# --- CORE ENGINE STABILITY ---
DpiAwareness = permonitor
AltTabFix = noactivateapp
ThreadPriorityBoost = off

# --- BALANCED PERFORMANCE ENGINE ---
CpuAffinity = all
CpuAffinityRotation = off
PresentDelay = on(10)
CompatFixes = nodwmflush

# --- GRAPHICS BACKBUFFER ---
SoftwareDevice = rgb
GdiInterops = all
VertexBufferMemoryType = sysmem

# --- DISPLAY ---
FullScreenMode = borderless
SupportedResolutions = native
DesktopResolution = desktop
DisplayResolution = desktop
DisplayAspectRatio = app
DisplayFilter = point
FpsLimiter = off
VSync = off